resources:
- name: app_code
  type: git
  source:
    uri: https://github.com/rajkamalhm/PCF.git

- name: deployment
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: xxxxxxxxxx
    password: xxxxxxxxxx
    organization: pcf-practice
    space: microservices
    skip_cert_check: false

jobs:
- name: simple-deploy
  plan:
  - get: app_code
    trigger: true
  - put: deployment
    params:
      manifest: app_code/flask_app/manifest.yml
      path: app_code/flask_app
